name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Définissez ici la branche sur laquelle vous souhaitez déclencher le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Clean gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{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}}
          publish_branch: gh-pages
          publish_dir: /
          force_orphan: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{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}}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
